In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


*Initialization of tensors*

In [2]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
x = tf.constant(4.0)
print(x)

tf.Tensor(4.0, shape=(), dtype=float32)


In [4]:
x = tf.constant(4, shape = (1,1), dtype = tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [5]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [6]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [7]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [8]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [9]:
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[0.47378832 1.5777427  0.59626496]
 [0.08354431 0.8266948  0.04841027]
 [0.9227894  1.637414   1.0906643 ]], shape=(3, 3), dtype=float32)


In [10]:
x = tf.random.uniform((1,3), minval=0, maxval=1)
print(x)

tf.Tensor([[0.8913195  0.34846556 0.53713286]], shape=(1, 3), dtype=float32)


In [11]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [12]:
x = tf.range(start = 1, limit = 10, delta = 2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [13]:
x = tf.cast(x, dtype = tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


*Mathematical Operations*

In [15]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

In [16]:
z = tf.add(x, y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [17]:
z = x+y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [18]:
z = tf.divide(x, y)

z = x/y

print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [20]:
z = tf.multiply(x,y)

z = x*y

print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [21]:
z = tf.tensordot(x, y, axes = 1)

z = tf.reduce_sum(x*y, axis = 0)

print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [22]:
z = x**5

print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [23]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z = tf.matmul(x,y)

z = x @ y

print(z)

tf.Tensor(
[[-1.5348881  -0.68109673 -1.1784587  -1.7365597 ]
 [-1.1037706  -1.4586078  -1.1217015  -0.05851461]], shape=(2, 4), dtype=float32)


*Indexing*

In [24]:
x = tf.constant([0,1,1,2,3,4,1,2])

print(x[1:])

tf.Tensor([1 1 2 3 4 1 2], shape=(7,), dtype=int32)


In [25]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [26]:
print(x[:6:2])

tf.Tensor([0 1 3], shape=(3,), dtype=int32)


In [27]:
print(x[::2])

tf.Tensor([0 1 3 1], shape=(4,), dtype=int32)


In [28]:
print(x[::-2])

tf.Tensor([2 4 2 1], shape=(4,), dtype=int32)


In [29]:
print(x[::-1])

tf.Tensor([2 1 4 3 2 1 1 0], shape=(8,), dtype=int32)


In [30]:
indices = tf.constant([0,3,4])

print(tf.gather(x, indices))

tf.Tensor([0 2 3], shape=(3,), dtype=int32)


*Reshaping*

In [31]:
x = tf.range(9)

x = tf.reshape(x, (3,3))

print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [32]:
x = tf.transpose(x)
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
